trino:
  target: dev
  outputs:
    dev:
      type: trino
      user: admin
      host: enode2
      port: 8080
      database: warehouse
      schema: bronze
      threads: 1

spark:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: enode1
      port: 10016
      schema: silver
      auth: NOSASL
      connect_retries: 3
      connect_timeout: 5
      retry_all: true

gold:
  target: dev
  outputs:
    dev:
      type: trino
      user: admin
      host: localhost
      port: 8080
      database: de_psql
      schema: gold
      threads: 1